name: 'Dotnet Workflow'
on: [push]
jobs:
  welcome:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello"

  build:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Build"

  test:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Test"

  publish:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Publish"
